"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

type Product={id:string;name:string;brand:string|null;sku:string|null;upc:string|null;price:number;is_active:boolean;is_featured:boolean;publication_status:string;inventory?:{quantity:number;low_stock_threshold:number}[]};

export default function AdminProducts(){
 const router=useRouter(); const [products,setProducts]=useState<Product[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/admin/products",{cache:"no-store"}).then(async r=>{if(r.status===401){router.replace("/admin/login");return;} const d=await r.json(); if(!r.ok)setError(d.error||"Error cargando productos."); else setProducts(d.products||[]); setLoading(false);});},[router]);
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();return !x?products:products.filter(p=>[p.name,p.brand,p.sku,p.upc].some(v=>v?.toLowerCase().includes(x)));},[products,q]);
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/10 px-6 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-sm font-semibold text-emerald-400">FIRST CHOICE PHARMACY</p><h1 className="text-xl font-bold">Productos</h1></div><Link href="/admin" className="rounded-xl border border-white/15 px-4 py-2 text-sm">← Dashboard</Link></div></header><div className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-3xl font-bold">Catálogo</h2><p className="mt-1 text-sm text-white/60">{products.length} productos cargados</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nombre, marca, SKU o UPC…" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 sm:max-w-md"/></div>{loading&&<p className="mt-8 text-white/60">Cargando productos…</p>}{error&&<p className="mt-8 rounded-xl bg-red-500/10 p-4 text-red-300">{error}</p>}{!loading&&!error&&<div className="mt-8 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-white/5 text-white/60"><tr><th className="p-4">Producto</th><th className="p-4">SKU / UPC</th><th className="p-4">Precio</th><th className="p-4">Stock</th><th className="p-4">Estado</th></tr></thead><tbody>{filtered.map(p=>{const inv=p.inventory?.[0];return <tr key={p.id} className="border-t border-white/10"><td className="p-4"><p className="font-semibold">{p.name}</p><p className="text-xs text-white/50">{p.brand||"Sin marca"}</p></td><td className="p-4 text-white/70">{p.sku||"—"}<br/><span className="text-xs">{p.upc||""}</span></td><td className="p-4 font-semibold">${Number(p.price).toFixed(2)}</td><td className="p-4">{inv?.quantity??0}{inv&&inv.quantity<=inv.low_stock_threshold&&<span className="ml-2 rounded-full bg-amber-500/15 px-2 py-1 text-xs text-amber-300">Bajo</span>}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${p.is_active?"bg-emerald-500/15 text-emerald-300":"bg-white/10 text-white/50"}`}>{p.is_active?"Activo":"Inactivo"}</span></td></tr>})}{filtered.length===0&&<tr><td colSpan={5} className="p-8 text-center text-white/50">No hay productos que coincidan.</td></tr>}</tbody></table></div>}</div></main>;
}
